backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: "src/markdown-pages/about.md"
        name: 'about'
        label: 'About'
        editor:
        preview: true
        fields:
          - {label: 'About', name: 'slug', widget: 'hidden', default: '/about'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Cona', name: 'cona', widget: 'image'}
      - file: "src/markdown-pages/index.md"
        name: 'Index'
        label: 'Intro'
        editor:
        preview: true
        fields:
          - {label: 'Index', name: 'slug', widget: 'hidden', default: '/'}
          - {label: 'Intro Title 1', name: 'introTitle1', widget: 'string'}
          - {label: 'Intro Title 2', name: 'introTitle2', widget: 'string'}
          - {label: 'Intro Description', name: 'introDescription', widget: 'string'}
          - {label: 'Intro Image', name: 'introImage', widget: 'image'}
          - {label: 'Colab Title', name: 'colabTitle', widget: 'string'}
          - {label: 'About Title 1', name: 'aboutTitle1', widget: 'string'}
          - {label: 'About Title 2', name: 'aboutTitle2', widget: 'string'}
          - {label: 'About Description', name: 'aboutDescription', widget: 'string'}
          - {label: 'About Send Email Name', name: 'aboutSendEmailName', widget: 'string'}
          
       
        